version: "3"

services:
  price-monitor:
    environment:
      - DD_AGENT_HOST=dd-agent
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://dd-agent:4317
      - DD_SERVICE=sqs-price-monitor
      - DD_ENV=prod
      - DD_VERSION=25.0.0
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: price-monitor
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "2048m"
        max-file: "3"
        tag: "{{.ImageName}}|{{.Name}}"

  dd-agent:
    image: gcr.io/datadoghq/agent:7
    container_name: price-monitor-dd-agent
    labels:
      com.datadoghq.ad.checks: |
        {
          "openmetrics": {
            "init_configs": [{}],
            "instances": [
              {
                "openmetrics_endpoint": "http://price-monitor:8080/metrics",
                "namespace": "pricemonitor",
                "metrics": 
                  [
                    "price_monitor_heartbeat",
                    "price_monitor_price_errors_total"
                  ]
              }
            ]
          }
        }
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=us5.datadoghq.com
      - DD_ENV=prod
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /proc/:/host/proc/:rw
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:rw
      - /var/lib/docker/containers:/var/lib/docker/containers:rw
      - /opt/datadog/apm:/opt/datadog/apm
    ports:
      - 4317:4317
      - 4318:4318
      - 8126:8126
